### ISSUE TITLE
Link to static asset is broken for code blocks in the `root_doc`

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-copybutton#121]
**Describe the bug**

https://github.com/executablebooks/sphinx-copybutton/blob/d13f7d188b116b656b732bcdefd34e5d9900902e/sphinx_copybutton/_static/copybutton.js_t#L85

The code uses `${DOCUMENTATION_OPTIONS.URL_ROOT}` to locate the static file. However, that is `#` for the `root_doc` when building on RTD (likely with `dirhtml`). This means that the link for the static asset is changed to `#_static/copy-button.svg`, which doesn't work.

**To Reproduce**

1. Build any Sphinx documentation with a code block in root_doc, and host it on RTD.
2. See missing image.

See https://cpython-devguide--679.org.readthedocs.build/ for example.

**Expected behavior**

The link to the image should be `_static/copy-button.svg`.

**Environment**

See https://readthedocs.org/projects/cpython-devguide/builds/13630239/, which is about as much as I know. :)

**Additional context**

Cross-referencing with https://github.com/python/devguide/pull/679, because... why not. :)

**Comment by choldgraf** [comment]
ah yeah - this definitely needs a better story around linking the proper libraries...TBH I had no idea what I was doing when I first set up this extension

**Comment by pablogsal** [comment]
We recently switched to use this extension in the Python devguide: https://devguide.python.org/, which is very cool, but unfortunately we are hitting this error in the front page. Is there any way we could help to solve this issue?

**Comment by choldgraf** [comment]
I _think_ we might be able to fix this by using `pathto(` jinja logic in the line that @pradyunsg notes above. For example, check out its use here in the pydata sphinx theme: https://github.com/pydata/pydata-sphinx-theme/blob/e5b9765d383ce6217d443053906a979b1da1f301/pydata_sphinx_theme/static/webpack-macros.html

**Comment by choldgraf** [comment]
Actually, I think it's more complicated than that. I've tried to fix it in #129 but hit a bunch of snags. Specifically:

- I tried using `pathto` directly in the `copybutton.js_t` file, but `pathto` was not yet defined, I think because it is only converted into a static file at the beginning of the build, not once per page.
- I tried defining a javascript variable with `pathto` and adding it to each page with `add_js_file(None, body="<my js>")`. However, this appends to the output HTML in an additive fashion, so we are adding more and more lines with each new page. This is fixed in more recent versions of Sphinx but won't work on older versions.

I think that's the reason we are using the URL_ROOT pattern described here. So perhaps the easiest thing to do is simply to do a JS string replacement to remove the leading `#` if the URL_ROOT begins with `#`.

**Comment by pradyunsg** [comment]
Can't we just have an if statement, for determining the prefix? We don't really need to do any fancy pathto stuff -- the existing logic works everywhere except on the root document, which we can special case?

```
if documentation root url == `#`:
    prefix = ""
else:
   prefix = documentation root url
```

**Comment by choldgraf** [comment]
> Am I missing something?

Nope i think you're just being more pragmatic then i am 😅

**Comment by pablogsal** [comment]
@choldgraf would you be ok with @pradyunsg workaround?

**Comment by choldgraf** [comment]
oh totally, sorry that wasn't clear in my post above haha
