### ISSUE TITLE
Copy blanklines on matches(?)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-copybutton#84]
Following #83 blanklines are not captured, e.g.

```python
In [1]: import something
   ...:
   ...: print(something.__version__)
```

If the regex is set, will copy:

```python
import something
print(something.__version__)
```

**Comment by choldgraf** [comment]
My intuition is that yes, we should copy them because the user is going to expect the output to look almost just like the copied code (minus prompts)

**Comment by chrisjsewell** [comment]
Also I can't figure this out, but in this repository I used:

```
copybutton_prompt_text = ">>> |\\\\$ |\\[\\d*\\]: |\\.\\.\\.: "
```

which appears to work fine.
but in aiida I've had to use:

```
copybutton_prompt_text = '>>> |\\\\$ |In \\\\[\\\\d\\\\]: |\\\\s+\\.\\.\\.: '
```

with the tonnes of backslashes, but this is what works

**Comment by chrisjsewell** [comment]
See: https://325-77234579-gh.circle-artifacts.com/0/html/intro/tutorial.html

**Comment by choldgraf** [comment]
god I hate regexes 😆

**Comment by amotl** [comment]
Dear Chris,

first things first: Thanks for your excellent work on this Sphinx addon, it really saves us.

We want to report back about what @chrisjsewell originally reported here. Apparently, we are getting tripped by this as well. For example, the code block at [1] will not get copied "as-is", all empty lines are missing. The config entries within `conf.py` we are currently using can be reviewed at [2].

Are we missing any respective configuration option here? Otherwise, do you see an easy way to make sphinx-copybutton pass through empty lines?

With kind regards,
Andreas.

[1] https://crate.io/docs/python/en/latest/sqlalchemy.html#tables
[2] https://github.com/crate/crate-docs-theme/blob/0.15.1/src/crate/theme/rtd/conf/__init__.py#L112-L115

**Comment by choldgraf** [comment]
I'm not quite sure where the fix needs to be for this unfortunately, and haven't had time to dig into the code to figure it out. If you or anybody else wants to take a look I am happy to review PRs! (maybe @sappelhof has run into this issue too?)

**Comment by amotl** [comment]
Thank you for the quick response. I tried to find the spot and handed in a corresponding patch with #127.

**Comment by sappelhoff** [comment]
>  (maybe @sappelhoff has run into this issue too?)

I haven't (yet), but I am glad that @amotl prepared a patch (and I would vote for making copying empty lines the default)

**Comment by amotl** [comment]
Thank you Stefan, appreciate it. Both bringing in the feature as well as making copying empty lines the default behavior have now been folded into #127.
